# Generated by Django 4.2.2 on 2024-10-15 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название привычки"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Место выполнения",
                    ),
                ),
                (
                    "time_action",
                    models.TimeField(verbose_name="Время когда нужно выполнить"),
                ),
                ("action", models.CharField(max_length=250, verbose_name="Действие")),
                (
                    "pleasant",
                    models.BooleanField(default=False, verbose_name="Приятная"),
                ),
                (
                    "period",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Периодичность в днях"
                    ),
                ),
                (
                    "prize",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Публичная"),
                ),
                (
                    "complete_time",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Время на выполнение"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
        ),
    ]
