# Generated by Django 4.2.2 on 2024-10-15 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"verbose_name": "Привычка", "verbose_name_plural": "Привычки"},
        ),
    ]
