# Generated by Django 4.2.2 on 2024-10-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time_action",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Время когда нужно выполнить"
            ),
        ),
    ]
